### ISSUE TITLE
release build cannot access css files

### ISSUE THREAD

**Issue by francois-pasquier** [tauri-apps/vue-cli-plugin-tauri#13]
Following exactly the README, nothing else, I have this issue:

`yarn tauri:serve` works fine but when I build the project with `yarn tauri:build`, the app displays fine but doesn't react to my interactions

Please note that I also tried installing the `.deb` package with debtap, I am getting the same error though

```
$: src-tauri/target/release/app
thread '<unnamed>' panicked at 'Could not read asset /home/chell/Sources/vue/tauri/my-tauri-app/dist_tauri/bundled/css/app.7f6daad7.css?__WB_REVISION__=b6a19a9d11c01ef9bea8: Custom { kind: NotFound, error: "Key not found" }', /home/chell/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.6.2/src/server.rs:10:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
src-tauri/target/release/app
thread '<unnamed>' panicked at 'Could not read asset /home/chell/Sources/vue/tauri/my-tauri-app/dist_tauri/bundled/css/app.7f6daad7.css?__WB_REVISION__=b6a19a9d11c01ef9bea8: Custom { kind: NotFound, error: "Key not found" }', /home/chell/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.6.2/src/server.rs:10:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$: ls -l dist_tauri/bundled/css
.rw-r--r-- 428 chell 26 juin  10:18 app.7f6daad7.css
```

I also tried starting fresh to avoid any HMR "side effects", the result is the same

**Comment by nklayman** [comment]
I just created a bug report issue template. Please create a new issue and fill out all the info asked for in the template. Without that information, I cannot reproduce your issue and therefore cannot debug it.
