### ISSUE TITLE
fail run in after release build

### ISSUE THREAD

**Issue by Stvchm9703** [tauri-apps/vue-cli-plugin-tauri#18]
**Describe the bug**
success run in develop mode , while fail run in after build 

**To Reproduce**
``` 
// create vue project 
vue create apps

cd apps/

// add vue cli plugin tauri 
vue add tauri

// build apps
yarn tauri:build

// success build 
```

then, open `apps/dist_tauri/release` and run the exe, the app render the index page and show white screen and no response 

**Expected behavior**
smooth run as `yarn tauri:serve`

**Screenshots**
screen shot that running `yarn tauri:serve`
![image](https://user-images.githubusercontent.com/15327054/89756940-77915c80-db16-11ea-810c-b9b2c4769504.png)

screen shot of after build release 
![image](https://user-images.githubusercontent.com/15327054/89756803-1e292d80-db16-11ea-8029-2b9ed0ba13d3.png)

**Environment (please complete the following information):**
####  npm package version ####
```json
 "dependencies": {
    "@vue/composition-api": "^1.0.0-beta.6",
    "register-service-worker": "^1.7.1",
    "vue": "^2.6.11",
    "vue-router": "^3.4.1",
    "vuex": "^3.5.1",
    "vuex-class": "^0.3.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-pwa": "^4.4.6",
    "@vue/cli-plugin-router": "^4.4.6",
    "@vue/cli-plugin-typescript": "^4.4.6",
    "@vue/cli-plugin-vuex": "^4.4.6",
    "@vue/cli-service": "~4.4.0",
    "node-sass": "^4.14.1",
    "pug": "^3.0.0",
    "pug-plain-loader": "^1.0.0",
    "sass": "^1.26.5",
    "sass-loader": "^9.0.3",
    "ts-loader": "^8.0.2",
    "typescript": "^3.9.7",
    "vue-cli-plugin-pug": "^1.0.7",
    "vue-cli-plugin-tauri": "~0.11.1",
    "vue-template-compiler": "^2.6.11"
  },
```

#### Tauri Info ####
[tauri]: running info

Operating System - Windows_NT(10.0.18363) - win32/x64
Microsoft Edge - 44.18362.449.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.6.0
  tauri.js - 0.11.1

Rust environment
  rustc - 1.47.0-nightly
  cargo - 1.47.0-nightly
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.6
  yarn - 1.19.1

App directory structure
/.git
/dist
/dist_tauri
/icons
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset

**Additional context**

**Comment by Stvchm9703** [comment]
maybe I try remove the file hashing later

**Comment by Stvchm9703** [comment]
solved for the init missing index page, it seem need to remove the file hashing in vue.config
``` js 
module.exports = {
    ...,
  filenameHashing: false,
...
}
```

but still, the apps run awhile and get no response!

**Comment by nklayman** [comment]
Can you try creating a non-vue Tauri app to see if it's an issue with this plugin or Tauri itself?

**Comment by Stvchm9703** [comment]
Basically, I try to create new one, it works.
Maybe I may check the build config?

**Comment by nklayman** [comment]
By "new one" do you mean a new vue-cli project or a new tauri (non vue) project? It's possible the cache may be causing an issue, try deleting the `dist_tauri` dir and rebuilding.

**Comment by Stvchm9703** [comment]
ok, I find the reason that the app run in Not-Responding, It need to remove  ` "@vue/cli-plugin-pwa": "^4.4.6",`

**Comment by Stvchm9703** [comment]
Can it keep it alive or label to potential risk ? Currently, I have no idea to solve this

**Comment by nklayman** [comment]
There was another issue with pwa support, #14. Try the solution there and see if that helps.
