### ISSUE TITLE
src/cmd.rs is gone?

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/vue-cli-plugin-tauri#30]
Do not have this file:
src-tauri/src/cmd.rs

and  vue project, window.open() , is not effect

**Comment by mxismean** [comment]
@jbolda please help me

**Comment by nklayman** [comment]
As of the 1.0.0-beta (and beta-rc), the cmd.rs file is no longer included in the template. See the new [command guide](https://tauri.studio/en/docs/usage/guides/command/) for instructions on creating commands with the new macros.
