### ISSUE TITLE
libwebkit2gtk-4.0 is not installable on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by fkromer** [tauri-apps/vue-cli-plugin-tauri#35]
**Describe the bug**

If one tries to install a tauri app bundled into a .deb package on Ubuntu 20.04 LTS one get's the error

```
(...)

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ta-unor-r-is : Depends: libwebkit2gtk-4.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Would be great if you could complete the docs about how to install the `webkit2` "runtime" dependency. I've installed `libwebkit2gtk-4.0-dev` to make it work probably but it did not help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : 
 - other vue plugins used: 
 - (if possible) link to your repo: https://github.com/fkromer/taunorris/tree/tauri
 - output from `npx tauri info`/`yarn tauri info`:

**Additional context**

**Comment by nklayman** [comment]
I believe this bug was fixed with the latest version of Tauri CLI. I just published a new version of the Vue plugin that updates the CLI. Try updating vue-cli-plugin-tauri, rebuilding, and that should fix it.
