### ISSUE TITLE
Cannot create tauri-apps / vue-cli-plugin-tauri successfully on win10 21H1

### ISSUE THREAD

**Issue by AWAUOX** [tauri-apps/vue-cli-plugin-tauri#42]
**Describe the bug**

When I try to install tauri-apps/vue-cli-plugin-tauri in a empty folder,and I don't know how to do,I have also tried to install with npm and yarn, but none of them succeeded,The following error occurred：

  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="D:\DevProgram\GUI\tauri\tauridemo\node_modules\optipng-bin\vendor" --bindir="D:\DevProgram\GUI\tauri\tauridemo\node_modules\optipng-bin\vendor""
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at D:\DevProgram\GUI\tauri\tauridemo\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! optipng-bin@7.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the optipng-bin@7.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AWACS\AppData\Roaming\npm-cache\_logs\2021-08-18T15_04_38_172Z-debug.log
 ERROR  command failed: npm install --loglevel error vue-cli-plugin-tauri -D
Error with command: npx
Error: Error: Command failed with exit code 1: npx @vue/cli add tauri --appName tauridemo --windowTitle Tauri App
    at C:\Users\AWACS\AppData\Roaming\npm-cache\_npx\18324\node_modules\create-tauri-app\dist\index.js:63:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\AWACS\AppData\Roaming\npm-cache\_npx\18324\node_modules\create-tauri-app\dist\index.js:40:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by ilopsource** [comment]
How did you solve it？I have the same problem

**Comment by lqomg** [comment]
How did you solve it？

**Comment by ilopsource** [comment]
> How did you solve it？

应该是网络问题，开了代理就好了
