### ISSUE TITLE
`vue add tauri` build error

### ISSUE THREAD

**Issue by bigdogs** [tauri-apps/vue-cli-plugin-tauri#43]
**Describe the bug**
vue-demo % vue add tauri

 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing vue-cli-plugin-tauri...

npm ERR! code 1
npm ERR! path /Users/admin/Desktop/vue-demo/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! (node:59918) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/admin/Desktop/vue-demo/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/16.3.0/bin/node" "/Users/admin/Desktop/vue-demo/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/admin/Desktop/vue-demo/node_modules/sharp
npm ERR! gyp ERR! node -v v16.3.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-09-01T12_25_30_769Z-debug.log
 ERROR  command failed: npm install --loglevel error vue-cli-plugin-tauri -D --legacy-peer-deps

**To Reproduce**

**Expected behavior**
install success without error

**Environment (please complete the following information):**
bigusr11.5.2  m1

**Comment by nothingismagick** [comment]
Oh jeez, we will have to move the tauri icon procedure out of the nodejs CLI...

**Comment by lucasfernog** [comment]
fatal error: 'vips/vips8' file not found

seems like you need to install vips

**Comment by bigdogs** [comment]
`brew install vips` solves this issue
