### ISSUE TITLE
Tauri freeze with a blank page on start with 1.0.0-rc.0

### ISSUE THREAD

**Issue by Silbad** [tauri-apps/vue-cli-plugin-tauri#61]
**Describe the bug**
Tauri starts with a blank page

**To Reproduce**
Upgrade to 1.0.0-rc.0, then start dev mode

**Environment (please complete the following information):**
 - OS : WIN11
 - vue-cli-plugin-tauri version : 1.0.0-rc.0
 - other vue plugins used: @tauri-apps/api 1.0.0-rc.0
 - output from `npx tauri info`/`yarn tauri info`: command not found: tauri

**Comment by billyadelphia** [comment]
Same issue here ..

**Comment by lucasfernog** [comment]
Fix published on 1.0.0-rc.1

**Comment by Silbad** [comment]
It works! Thank you for your reactivity!
