### ISSUE TITLE
run failed according https://github.com/tauri-apps/vue-cli-plugin-tauri/README  in win10

### ISSUE THREAD

**Issue by iot-lorawan** [tauri-apps/vue-cli-plugin-tauri#62]
**Describe the bug**
![图片](https://user-images.githubusercontent.com/30143031/153813520-11150ec5-28f6-46e0-96fd-3ce0c3a4758a.png)

**To Reproduce**

insatll and run according https://github.com/tauri-apps/vue-cli-plugin-tauri/README  in win10

**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : 
 - other vue plugins used: 
 - (if possible) link to your repo: 
 - output from `npx tauri info`/`yarn tauri info`:

![图片](https://user-images.githubusercontent.com/30143031/153813783-313acdf1-0c0f-429d-b6c1-d1773019bf52.png)

**Additional context**

**Comment by amrbashir** [comment]
It seems like you don't have webview2 runtime installed. Try installing it and report back with `npm run tauri info` if the issue presists.
