### ISSUE TITLE
thread 'main' panicked at 'error while running tauri application: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system could not find the specified file

### ISSUE THREAD

**Issue by yugangtan** [tauri-apps/vue-cli-plugin-tauri#68]
**Describe the bug**
when run script 'tauri:serve',
```
thread 'main' panicked at 'error while running tauri application: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system could not find the specified file。
, win32_error: 2 }))))', src\main.rs:9:6
```

**Comment by FabianLars** [comment]
You need to have WebView2 installed, please follow the instructions at https://tauri.studio/docs/getting-started/setting-up-windows

**Comment by checkwoodson** [comment]
this is url invalid!!

**Comment by FabianLars** [comment]
Here's the new url https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows

**Comment by checkwoodson** [comment]
thank you i install edge web in webView2. so is run all .
i think maybe no run reduce of webView2 lack.
