### ISSUE TITLE
vue-cli-service is not recognized as an internal or external command when using Vite built

### ISSUE THREAD

**Issue by VividLemon** [tauri-apps/vue-cli-plugin-tauri#70]
**Describe the bug**
This might not necessarily be your problem, or something to fix. But would be appreciated to get working correctly.
The documentation works fine, creating a vue cli project, and using vue add tauri. It works. However, when using "npm init vue@latest" to create a vue app, it uses Vite. This causes an error.
**To Reproduce**
1. use "npm init vue@latest" from https://vuejs.org/guide/quick-start.html#with-build-tools
2. Skip to step two of https://github.com/tauri-apps/vue-cli-plugin-tauri "vue add tauri"
3. Run yarn tauri:build

**Expected behavior**
It should build
**Screenshots**
Not applicable
**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : ~1.0.0-rc.2
 - other vue plugins used: vite
 - (if possible) link to your repo: 
 - output from `npx tauri info`/`yarn tauri info`:
```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.47
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.7 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: unset
  › distDir: Set automatically by Vue CLI plugin
  › devPath: Set automatically by Vue CLI plugin
  › framework: Vue.js
```

**Additional context**
It's really more of a QOL thing considering vue prefers using Vite over vue cli

**Comment by nklayman** [comment]
vue-cli-plugin-tauri only works with Vue CLI, not with Vite. For creating a Vite-based Tauri project, use [create-tauri-app](https://tauri.studio/v1/guides/getting-started/beginning-tutorial) and select the Vite option.
