### ISSUE TITLE
yarn tauri:build err

### ISSUE THREAD

**Issue by dongjiahong** [tauri-apps/vue-cli-plugin-tauri#71]
**Describe the bug**
can't build,

![image](https://user-images.githubusercontent.com/11733399/169738135-89b25380-76b7-454e-88f7-3428e0cc979f.png)

**To Reproduce**
1. vue create app
2. cd app
3. vue add tauri
4. yarn tauri:build

**Expected behavior**
it can build success.

**Environment (please complete the following information):**

```sh
yarn run v1.22.17
$ /Users/lele/develop/tauri-app/monitor/node_modules/.bin/tauri info

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.11,
  › tauri-build [RUST]: 1.0.0-rc.9,
  › tao [RUST]: 0.8.5,
  › wry [RUST]: 0.16.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: Set automatically by Vue CLI plugin
  › devPath: Set automatically by Vue CLI plugin
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  └─ src
✨  Done in 15.41s.
```

**Additional context**

**Comment by wisarmy** [comment]
I had the same problem and curve solved it as follows, please try.
1. update `@tauri-apps/cli` to latest, use `yarn add -D @tauri-apps/cli`
2. modify src-tauri/tauri.conf.json 
eg:
 ```
	"build": {
		"distDir": "../build",
		"devPath": "http://localhost:8080",
		"beforeDevCommand": "yarn serve",
		"beforeBuildCommand": "yarn build"
	},
```
3. run `yarn tauri dev` 

In addition when use `yan tauri build`, the app is blank

**Comment by lucasfernog** [comment]
This is just a problem of an outdated CLI, follow the above steps and you'll be good :)

**Comment by lucasfernog** [comment]
Ahh just realized this is a vue cli plugin issue, i'll fix and release it so you can update it.

**Comment by lucasfernog** [comment]
Update `vue-cli-plugin-tauri` to `1.0.0-rc.3` and try again :)
