### ISSUE TITLE
How do I turn off lintOnSave

### ISSUE THREAD

**Issue by Sunnnner** [tauri-apps/vue-cli-plugin-tauri#74]
![image](https://user-images.githubusercontent.com/9432907/172126402-d1ccfb22-990c-4a3f-974d-511265b37b60.png)

![image](https://user-images.githubusercontent.com/9432907/172126444-dfea5530-c587-415d-aad4-42e2b0f11153.png)

**Comment by nklayman** [comment]
This issue is related to Vue CLI, not this plugin. Please ask for help on one of their forums.
