### ISSUE TITLE
Tauri CLI crate not installed

### ISSUE THREAD

**Issue by Sombian** [tauri-apps/vue-cli-plugin-tauri#9]
greetings,

yesterday i had a problem where ``vue add tauri`` throw ``Tauri CLI crate not installed`` error.
this was solved by install ``tauri`` globally however.
would be glad to see even scoped install works.

best of luck.

**Comment by nklayman** [comment]
Fixed in version v0.0.6, the issue was that the plugin was checking for the `tauri-cli` rust crate which has been replaced by `tauri-bundler`.
